server:
  port: 8084



spring:
  web:
    resources:
      static-locations: file:src/main/resources/static/
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        show_sql: true


logging:
  level:
      org:
      hibernate:
      type:
      descriptor:
      sql: trace

